create table if not exists public.profiles (
  id uuid primary key,
  display_name text not null check (char_length(trim(display_name)) between 2 and 24),
  email text,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.profiles enable row level security;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name, email)
  values (
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'display_name'), ''), split_part(new.email, '@', 1)),
    new.email
  )
  on conflict (id) do update
  set
    display_name = excluded.display_name,
    email = excluded.email;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

insert into public.profiles (id, display_name, email)
select
  id,
  coalesce(nullif(trim(raw_user_meta_data ->> 'display_name'), ''), split_part(email, '@', 1)),
  email
from auth.users
on conflict (id) do update
set
  display_name = excluded.display_name,
  email = excluded.email;

drop policy if exists "Profiles are viewable by everyone" on public.profiles;
drop policy if exists "Users can view own profile" on public.profiles;
create policy "Users can view own profile"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

create table if not exists public.board_posts (
  id bigint generated by default as identity primary key,
  user_id uuid default auth.uid(),
  author text not null check (char_length(trim(author)) between 2 and 24),
  title text not null check (char_length(trim(title)) between 2 and 80),
  content text not null check (char_length(trim(content)) between 5 and 2000),
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.board_posts
  add column if not exists user_id uuid,
  add column if not exists author text,
  add column if not exists title text,
  add column if not exists content text,
  add column if not exists created_at timestamptz not null default timezone('utc', now());

alter table public.board_posts
  alter column user_id set default auth.uid();

create or replace function public.handle_board_post_author()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'authentication required';
  end if;

  new.user_id := auth.uid();

  select trim(display_name)
    into new.author
  from public.profiles
  where id = auth.uid();

  if new.author is null then
    raise exception 'profile not found';
  end if;

  return new;
end;
$$;

drop trigger if exists set_board_post_author on public.board_posts;
create trigger set_board_post_author
before insert on public.board_posts
for each row execute function public.handle_board_post_author();

create index if not exists board_posts_created_at_idx
  on public.board_posts (created_at desc);

create index if not exists board_posts_user_id_idx
  on public.board_posts (user_id);

alter table public.board_posts enable row level security;

drop policy if exists "Anyone can read board posts" on public.board_posts;
create policy "Anyone can read board posts"
on public.board_posts
for select
to anon, authenticated
using (true);

drop policy if exists "Anyone can insert board posts" on public.board_posts;
drop policy if exists "Authenticated users can insert board posts" on public.board_posts;
create policy "Authenticated users can insert board posts"
on public.board_posts
for insert
to authenticated
with check (auth.uid() = user_id);
