create table if not exists public.board_posts (
  id bigint generated by default as identity primary key,
  author text not null check (char_length(trim(author)) between 2 and 24),
  title text not null check (char_length(trim(title)) between 2 and 80),
  content text not null check (char_length(trim(content)) between 5 and 2000),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists board_posts_created_at_idx
  on public.board_posts (created_at desc);

alter table public.board_posts enable row level security;

drop policy if exists "Anyone can read board posts" on public.board_posts;
create policy "Anyone can read board posts"
on public.board_posts
for select
to anon, authenticated
using (true);

drop policy if exists "Anyone can insert board posts" on public.board_posts;
create policy "Anyone can insert board posts"
on public.board_posts
for insert
to anon, authenticated
with check (true);
